vim.desktop: ...
        echo ... > %\colorbox{yellow}{LINGUAS}%
        $(MSGFMT) ...
        rm -f %\colorbox{yellow}{LINGUAS}%

gvim.desktop: ...
        echo ... > %\colorbox{yellow}{LINGUAS}%
        $(MSGFMT) ...
        rm -f %\colorbox{yellow}{LINGUAS}%